# 📊 E-Commerce Sales Data Analysis
### Day 8 — Pandas Data Analysis Notebook

This notebook analyzes an e-commerce sales dataset using **Pandas**. It covers:

1. Loading & inspecting the dataset
2. Data selection & filtering
3. Sorting operations
4. `groupby()` and aggregation functions
5. Category-wise, city-wise, product-wise, and payment-method-wise analysis
6. Key statistics — total sales, average sales, highest/lowest sales, total quantity sold, number of orders
7. Top performers and specific-order lookups
8. Final observations

**Dataset:** `Day8_Ecommerce_Sales_Dataset.csv`

## 1. Setup & Load Data

In [1]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)
pd.set_option('display.width', 120)

# Load the dataset
df = pd.read_csv('Day8_Ecommerce_Sales_Dataset.csv')

print("Shape of dataset:", df.shape)
df.head()

Shape of dataset: (100, 13)

,Order_ID,Order_Date,Customer,City,Region,Category,Product,Quantity,Unit_Price,Discount_Percent,Total_Sales,Rating,Payment_Method
0,1001,2026-02-27,Kabir Ali,Hyderabad,South,Electronics,Wireless Headphones,3,1499,0,4497.00,3.8,Cash on Delivery
1,1002,2026-01-24,Aditya Verma,Jammu,North,Sports,Running Shoes,1,2799,0,2799.00,4.1,Cash on Delivery
2,1003,2026-04-18,Sara Ahmed,Chennai,South,Electronics,Power Bank,2,1199,15,2038.30,4.6,Cash on Delivery
3,1004,2026-03-13,Kabir Ali,Lucknow,North,Electronics,Mechanical Keyboard,4,2499,5,9496.20,4.1,Debit Card
4,1005,2026-03-30,Priya Menon,Jammu,North,Electronics,Smart Watch,1,3299,5,3134.05,4.2,UPI

In [2]:
# Basic info about the dataset
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          100 non-null    int64
 1   Order_Date        100 non-null    str
 2   Customer          100 non-null    str
 3   City              100 non-null    str
 4   Region            100 non-null    str
 5   Category          100 non-null    str
 6   Product           100 non-null    str
 7   Quantity          100 non-null    int64
 8   Unit_Price        100 non-null    int64
 9   Discount_Percent  100 non-null    int64
 10  Total_Sales       100 non-null    float64
 11  Rating            100 non-null    float64
 12  Payment_Method    100 non-null    str
dtypes: float64(2), int64(4), str(7)
memory usage: 10.3 KB

In [3]:
# Check for missing values
df.isnull().sum()

Order_ID            0
Order_Date          0
Customer            0
City                0
Region              0
Category            0
Product             0
Quantity            0
Unit_Price          0
Discount_Percent    0
Total_Sales         0
Rating              0
Payment_Method      0
dtype: int64

In [4]:
# Convert Order_Date to datetime for proper handling
df['Order_Date'] = pd.to_datetime(df['Order_Date'])
df.dtypes

Order_ID                     int64
Order_Date          datetime64[us]
Customer                       str
City                           str
Region                         str
Category                       str
Product                        str
Quantity                     int64
Unit_Price                   int64
Discount_Percent             int64
Total_Sales                float64
Rating                     float64
Payment_Method                 str
dtype: object

In [5]:
# Statistical summary of numeric columns
df.describe()

          Order_ID           Order_Date    Quantity   Unit_Price  Discount_Percent   Total_Sales      Rating
count   100.000000                  100  100.000000   100.000000        100.000000    100.000000  100.000000
mean   1050.500000  2026-04-02 03:07:12    2.940000  1647.000000          6.500000   4472.629500    4.322000
min    1001.000000  2026-01-01 00:00:00    1.000000   499.000000          0.000000    449.100000    3.500000
25%    1025.750000  2026-02-23 00:00:00    2.000000   799.000000          0.000000   1948.050000    4.100000
50%    1050.500000  2026-03-29 00:00:00    3.000000  1499.000000          5.000000   3228.300000    4.300000
75%    1075.250000  2026-05-16 00:00:00    4.000000  2499.000000         11.250000   6427.562500    4.700000
max    1100.000000  2026-06-30 00:00:00    5.000000  3499.000000         15.000000  13995.000000    5.000000
std      29.011492                  NaN    1.391315   970.054669          6.092718   3324.306691    0.414285

## 2. Data Selection
Selecting specific columns and rows using label-based (`.loc`) and position-based (`.iloc`) indexing.

In [6]:
# Select specific columns
df[['Order_ID', 'Product', 'Category', 'City', 'Total_Sales']].head()

   Order_ID              Product     Category       City  Total_Sales
0      1001  Wireless Headphones  Electronics  Hyderabad      4497.00
1      1002        Running Shoes       Sports      Jammu      2799.00
2      1003           Power Bank  Electronics    Chennai      2038.30
3      1004  Mechanical Keyboard  Electronics    Lucknow      9496.20
4      1005          Smart Watch  Electronics      Jammu      3134.05

In [7]:
# Select rows using iloc (first 5 rows, first 6 columns)
df.iloc[0:5, 0:6]

   Order_ID Order_Date      Customer       City Region     Category
0      1001 2026-02-27     Kabir Ali  Hyderabad  South  Electronics
1      1002 2026-01-24  Aditya Verma      Jammu  North       Sports
2      1003 2026-04-18    Sara Ahmed    Chennai  South  Electronics
3      1004 2026-03-13     Kabir Ali    Lucknow  North  Electronics
4      1005 2026-03-30   Priya Menon      Jammu  North  Electronics

In [8]:
# Select rows using loc with a condition, showing specific columns
df.loc[df['Category'] == 'Electronics', ['Product', 'City', 'Total_Sales', 'Payment_Method']].head()

                Product       City  Total_Sales    Payment_Method
0   Wireless Headphones  Hyderabad      4497.00  Cash on Delivery
2            Power Bank    Chennai      2038.30  Cash on Delivery
3   Mechanical Keyboard    Lucknow      9496.20        Debit Card
4           Smart Watch      Jammu      3134.05               UPI
14  Wireless Headphones    Kolkata      2998.00               UPI

## 3. Filtering Data

In [9]:
# Orders where Total_Sales is greater than 5000
high_value_orders = df[df['Total_Sales'] > 5000]
print(f"Number of high-value orders (> 5000): {len(high_value_orders)}")
high_value_orders[['Order_ID', 'Product', 'City', 'Total_Sales']].head()

Number of high-value orders (> 5000): 35

    Order_ID              Product       City  Total_Sales
3       1004  Mechanical Keyboard    Lucknow      9496.20
7       1008               Hoodie      Jammu      6076.20
9       1010               Jacket      Kochi      8996.40
10      1011         Coffee Maker  Hyderabad      6998.00
12      1013               Jacket    Lucknow     10620.75

In [10]:
# Orders paid via UPI in the South region
upi_south = df[(df['Payment_Method'] == 'UPI') & (df['Region'] == 'South')]
print(f"UPI orders from South region: {len(upi_south)}")
upi_south[['Order_ID', 'Customer', 'City', 'Product', 'Total_Sales']]

UPI orders from South region: 9

    Order_ID      Customer       City             Product  Total_Sales
10      1011     Rahul Das  Hyderabad        Coffee Maker      6998.00
18      1019  Reyansh Jain    Chennai              Jacket      7497.00
19      1020    Mehak Bhat    Chennai       Mixer Grinder      2999.00
24      1025   Rohan Mehta    Chennai            Football      3995.00
29      1030   Karan Joshi  Bengaluru  Python Programming      2996.00
41      1042     Manya Rao      Kochi        Water Bottle      3495.00
43      1044   Hiba Sheikh    Chennai             T-Shirt      1518.10
46      1047    Sana Malik  Bengaluru      Wireless Mouse      3820.75
63      1064    Aman Kumar      Kochi       Atomic Habits      2396.00

In [11]:
# Orders with a discount applied (Discount_Percent > 0) and rating >= 4.5
good_discounted_orders = df[(df['Discount_Percent'] > 0) & (df['Rating'] >= 4.5)]
print(f"Discounted orders with rating >= 4.5: {len(good_discounted_orders)}")
good_discounted_orders[['Order_ID', 'Product', 'Discount_Percent', 'Rating', 'Total_Sales']]

Discounted orders with rating >= 4.5: 32

    Order_ID                  Product  Discount_Percent  Rating  Total_Sales
2       1003               Power Bank                15     4.6      2038.30
9       1010                   Jacket                10     4.7      8996.40
11      1012              Cricket Bat                10     4.6      4498.20
12      1013                   Jacket                15     4.8     10620.75
20      1021                 Yoga Mat                10     4.7       809.10
21      1022            The Alchemist                 5     4.5       948.10
26      1027                 Football                15     4.6      3395.75
27      1028      Wireless Headphones                 5     4.6      5696.20
31      1032            Atomic Habits                10     4.5      1078.20
32      1033            Mixer Grinder                10     4.7      8097.30
34      1035             Coffee Maker                15     4.7      2974.15
36      1037               Power Bank                15     4.8      2038.30
37      1038             Dumbbell Set                 5     5.0      9495.25
40      1041             Coffee Maker                 5     4.6      6648.10
55      1056             Dumbbell Set                 5     5.0      3798.10
56      1057             Coffee Maker                15     4.5      8922.45
59      1060             Dumbbell Set                10     5.0      5397.30
60      1061       Python Programming                 5     5.0       711.55
62      1063            The Alchemist                10     4.8       449.10
64      1065       Python Programming                15     4.7      1273.30
65      1066              Smart Watch                10     4.7      5938.20
68      1069           Wireless Mouse                 5     4.7      1708.10
70      1071             Water Bottle                10     4.5      2516.40
72      1073            Atomic Habits                15     4.6      2545.75
73      1074            Atomic Habits                10     5.0       539.10
74      1075                    Jeans                15     4.5      3228.30
76      1077          Electric Kettle                 5     4.5      5696.20
77      1078  Machine Learning Basics                10     4.7       899.10
81      1082                 Yoga Mat                15     4.5      2292.45
85      1086                    Jeans                15     4.8      3228.30
87      1088       Python Programming                15     4.5      2546.60
92      1093              Cricket Bat                15     4.5      8496.60

In [12]:
# Orders for the 'Electronics' category with Quantity greater than 2
electronics_bulk = df[(df['Category'] == 'Electronics') & (df['Quantity'] > 2)]
electronics_bulk[['Order_ID', 'Product', 'City', 'Quantity', 'Total_Sales']]

    Order_ID              Product        City  Quantity  Total_Sales
0       1001  Wireless Headphones   Hyderabad         3      4497.00
3       1004  Mechanical Keyboard     Lucknow         4      9496.20
25      1026  Wireless Headphones  Chandigarh         3      4497.00
27      1028  Wireless Headphones  Chandigarh         4      5696.20
28      1029  Wireless Headphones   Hyderabad         4      5696.20
46      1047       Wireless Mouse   Bengaluru         5      3820.75
51      1052  Mechanical Keyboard  Chandigarh         4      9496.20
61      1062  Mechanical Keyboard      Mumbai         3      7497.00
75      1076  Wireless Headphones     Chennai         4      5996.00
83      1084       Wireless Mouse     Kolkata         5      4045.50
91      1092  Wireless Headphones   Ahmedabad         3      4497.00

## 4. Sorting Data

In [13]:
# Top 10 orders by Total_Sales (descending)
top10_sales = df.sort_values(by='Total_Sales', ascending=False).head(10)
top10_sales[['Order_ID', 'Product', 'City', 'Total_Sales']]

    Order_ID              Product        City  Total_Sales
48      1049        Running Shoes      Mumbai     13995.00
52      1053        Running Shoes   Hyderabad     13295.25
84      1085         Coffee Maker   Hyderabad     12596.40
89      1090          Cricket Bat     Lucknow     12495.00
12      1013               Jacket     Lucknow     10620.75
47      1048         Coffee Maker     Lucknow     10497.00
69      1070               Jacket       Delhi      9996.00
79      1080               Jacket       Delhi      9996.00
51      1052  Mechanical Keyboard  Chandigarh      9496.20
3       1004  Mechanical Keyboard     Lucknow      9496.20

In [14]:
# Lowest 5 orders by Total_Sales (ascending)
lowest5_sales = df.sort_values(by='Total_Sales', ascending=True).head(5)
lowest5_sales[['Order_ID', 'Product', 'City', 'Total_Sales']]

    Order_ID             Product        City  Total_Sales
5       1006       The Alchemist       Kochi       449.10
62      1063       The Alchemist  Chandigarh       449.10
73      1074       Atomic Habits     Lucknow       539.10
96      1097             T-Shirt      Mumbai       679.15
60      1061  Python Programming   Bengaluru       711.55

In [15]:
# Sort by Category (asc) then Total_Sales (desc) - useful for viewing top orders within each category
df.sort_values(by=['Category', 'Total_Sales'], ascending=[True, False]).head(10)[
    ['Category', 'Product', 'City', 'Total_Sales']]

   Category                  Product       City  Total_Sales
99    Books    Data Science Handbook       Pune      4495.00
29    Books       Python Programming  Bengaluru      2996.00
90    Books            Atomic Habits      Kochi      2995.00
87    Books       Python Programming    Lucknow      2546.60
72    Books            Atomic Habits    Kolkata      2545.75
63    Books            Atomic Habits      Kochi      2396.00
66    Books            The Alchemist     Mumbai      2245.50
86    Books            Atomic Habits    Kolkata      2036.60
98    Books  Machine Learning Basics  Ahmedabad      1998.00
88    Books  Machine Learning Basics   Srinagar      1798.20

In [16]:
# Sort by Rating to see best and worst rated orders
best_rated = df.sort_values(by='Rating', ascending=False).head(5)
best_rated[['Order_ID', 'Product', 'Rating', 'Total_Sales']]

    Order_ID       Product  Rating  Total_Sales
24      1025      Football     5.0      3995.00
35      1036      Yoga Mat     5.0      1798.00
47      1048  Coffee Maker     5.0     10497.00
37      1038  Dumbbell Set     5.0      9495.25
55      1056  Dumbbell Set     5.0      3798.10

## 5. Overall Key Statistics
Total sales, average sales, highest/lowest sales, total quantity sold, and number of orders — for the entire dataset.

In [17]:
total_sales = df['Total_Sales'].sum()
average_sales = df['Total_Sales'].mean()
highest_sale = df['Total_Sales'].max()
lowest_sale = df['Total_Sales'].min()
total_quantity = df['Quantity'].sum()
number_of_orders = df['Order_ID'].nunique()

print(f"Total Sales          : ₹{total_sales:,.2f}")
print(f"Average Sales/Order   : ₹{average_sales:,.2f}")
print(f"Highest Single Sale   : ₹{highest_sale:,.2f}")
print(f"Lowest Single Sale    : ₹{lowest_sale:,.2f}")
print(f"Total Quantity Sold   : {total_quantity} units")
print(f"Number of Orders      : {number_of_orders}")

Total Sales          : ₹447,262.95
Average Sales/Order   : ₹4,472.63
Highest Single Sale   : ₹13,995.00
Lowest Single Sale    : ₹449.10
Total Quantity Sold   : 294 units
Number of Orders      : 100

In [18]:
# The order with the highest and lowest sale amount
highest_order = df.loc[df['Total_Sales'].idxmax()]
lowest_order = df.loc[df['Total_Sales'].idxmin()]

print("Highest sale order:")
print(highest_order[['Order_ID', 'Product', 'City', 'Total_Sales']])
print("\nLowest sale order:")
print(lowest_order[['Order_ID', 'Product', 'City', 'Total_Sales']])

Highest sale order:
Order_ID                1049
Product        Running Shoes
City                  Mumbai
Total_Sales          13995.0
Name: 48, dtype: object

Lowest sale order:
Order_ID                1006
Product        The Alchemist
City                   Kochi
Total_Sales            449.1
Name: 5, dtype: object

## 6. Category-wise Analysis
Using `groupby()` and aggregation functions (`sum`, `mean`, `max`, `min`, `count`) to analyze sales by product category.

In [19]:
category_analysis = df.groupby('Category').agg(
    Total_Sales=('Total_Sales', 'sum'),
    Average_Sales=('Total_Sales', 'mean'),
    Highest_Sale=('Total_Sales', 'max'),
    Lowest_Sale=('Total_Sales', 'min'),
    Total_Quantity=('Quantity', 'sum'),
    Number_of_Orders=('Order_ID', 'count')
).round(2).sort_values(by='Total_Sales', ascending=False)

category_analysis

                Total_Sales  Average_Sales  Highest_Sale  Lowest_Sale  Total_Quantity  Number_of_Orders
Category
Sports            136026.45        5441.06      13995.00       759.05              79                25
Home & Kitchen    113329.90        5396.66      12596.40      1188.30              59                21
Electronics        92086.00        4846.63       9496.20      1708.10              57                19
Clothing           69028.20        4930.59      10620.75       679.15              39                14
Books              36792.40        1752.02       4495.00       449.10              60                21

In [20]:
# Best performing category by total sales
top_category = category_analysis['Total_Sales'].idxmax()
print(f"🏆 Top-performing category: {top_category}")
print(f"   Total Sales: ₹{category_analysis.loc[top_category, 'Total_Sales']:,.2f}")

🏆 Top-performing category: Sports
   Total Sales: ₹136,026.45

## 7. City-wise Analysis

In [21]:
city_analysis = df.groupby('City').agg(
    Total_Sales=('Total_Sales', 'sum'),
    Average_Sales=('Total_Sales', 'mean'),
    Total_Quantity=('Quantity', 'sum'),
    Number_of_Orders=('Order_ID', 'count')
).round(2).sort_values(by='Total_Sales', ascending=False)

city_analysis

             Total_Sales  Average_Sales  Total_Quantity  Number_of_Orders
City
Hyderabad       59076.45        8439.49              25                 7
Chennai         47493.20        4749.32              29                10
Lucknow         46194.65        7699.11              22                 6
Pune            41908.55        4190.86              34                10
Mumbai          41457.80        5182.23              23                 8
Kochi           37257.50        4139.72              29                 9
Chandigarh      34539.65        4317.46              22                 8
Delhi           30882.80        5147.13              18                 6
Jaipur          25534.00        3647.71              17                 7
Kolkata         20169.00        2881.29              24                 7
Jammu           16059.75        2676.62              11                 6
Ahmedabad       14788.70        2464.78              12                 6
Bengaluru       13524.30        3381.08              14                 4
Srinagar        11778.60        2355.72              12                 5
Bhubaneswar      6598.00        6598.00               2                 1

In [22]:
# Top 5 cities by total sales
top5_cities = city_analysis.head(5)
print("🏙️ Top 5 cities by total sales:")
top5_cities

🏙️ Top 5 cities by total sales:

           Total_Sales  Average_Sales  Total_Quantity  Number_of_Orders
City
Hyderabad     59076.45        8439.49              25                 7
Chennai       47493.20        4749.32              29                10
Lucknow       46194.65        7699.11              22                 6
Pune          41908.55        4190.86              34                10
Mumbai        41457.80        5182.23              23                 8

In [23]:
# Region-wise sales (Region column also available)
region_analysis = df.groupby('Region').agg(
    Total_Sales=('Total_Sales', 'sum'),
    Average_Sales=('Total_Sales', 'mean'),
    Number_of_Orders=('Order_ID', 'count')
).round(2).sort_values(by='Total_Sales', ascending=False)

region_analysis

        Total_Sales  Average_Sales  Number_of_Orders
Region
North     164989.45        4341.83                38
South     157351.45        5245.05                30
West       98155.05        4089.79                24
East       26767.00        3345.88                 8

## 8. Product-wise Analysis

In [24]:
product_analysis = df.groupby('Product').agg(
    Total_Sales=('Total_Sales', 'sum'),
    Average_Sales=('Total_Sales', 'mean'),
    Total_Quantity=('Quantity', 'sum'),
    Number_of_Orders=('Order_ID', 'count')
).round(2).sort_values(by='Total_Sales', ascending=False)

product_analysis

                         Total_Sales  Average_Sales  Total_Quantity  Number_of_Orders
Product
Coffee Maker                51610.25        7372.89              16                 7
Jacket                      47106.15        9421.23              20                 5
Cricket Bat                 41483.40        8296.68              18                 5
Running Shoes               41285.25        8257.05              15                 5
Wireless Headphones         33877.40        4839.63              23                 7
Dumbbell Set                30184.90        6036.98              16                 5
Mechanical Keyboard         26489.40        8829.80              11                 3
Electric Kettle             26382.40        5276.48              19                 5
Mixer Grinder               25341.55        6335.39               9                 4
Smart Watch                 15670.25        5223.42               5                 3
Yoga Mat                    12765.80        2127.63              16                 6
Atomic Habits               11590.65        1931.78              21                 6
Football                    10307.10        2576.78              14                 4
Water Bottle                 9995.70        1999.14              15                 5
Wireless Mouse               9574.35        3191.45              12                 3
T-Shirt                      7790.25        1558.05              10                 5
Hoodie                       7675.20        3837.60               5                 2
Python Programming           7527.45        1881.86              11                 4
The Alchemist                7485.00        1247.50              17                 6
Power Bank                   6474.60        2158.20               6                 3
Jeans                        6456.60        3228.30               4                 2
Machine Learning Basics      5694.30        1423.58               6                 4
Data Science Handbook        4495.00        4495.00               5                 1

In [25]:
# Top 5 best-selling products by total sales
top5_products = product_analysis.head(5)
print("🥇 Top 5 products by total sales:")
top5_products

🥇 Top 5 products by total sales:

                     Total_Sales  Average_Sales  Total_Quantity  Number_of_Orders
Product
Coffee Maker            51610.25        7372.89              16                 7
Jacket                  47106.15        9421.23              20                 5
Cricket Bat             41483.40        8296.68              18                 5
Running Shoes           41285.25        8257.05              15                 5
Wireless Headphones     33877.40        4839.63              23                 7

In [26]:
# Product with the highest quantity sold
top_qty_product = product_analysis['Total_Quantity'].idxmax()
print(f"📦 Product with highest quantity sold: {top_qty_product} "
      f"({product_analysis.loc[top_qty_product, 'Total_Quantity']} units)")

📦 Product with highest quantity sold: Wireless Headphones (23 units)

## 9. Payment Method Analysis

In [27]:
payment_analysis = df.groupby('Payment_Method').agg(
    Total_Sales=('Total_Sales', 'sum'),
    Average_Sales=('Total_Sales', 'mean'),
    Number_of_Orders=('Order_ID', 'count')
).round(2).sort_values(by='Total_Sales', ascending=False)

payment_analysis

                  Total_Sales  Average_Sales  Number_of_Orders
Payment_Method
Credit Card         106540.25        4842.74                22
Debit Card           98064.90        4903.25                20
Net Banking          96371.25        5668.90                17
UPI                  96163.25        3698.59                26
Cash on Delivery     50123.30        3341.55                15

In [28]:
# Most popular payment method by number of orders
most_popular_payment = payment_analysis['Number_of_Orders'].idxmax()
print(f"💳 Most used payment method: {most_popular_payment} "
      f"({payment_analysis.loc[most_popular_payment, 'Number_of_Orders']} orders)")

💳 Most used payment method: UPI (26 orders)

## 10. Multi-level Grouping
Combining `groupby()` on multiple columns for deeper insights.

In [29]:
# Category-wise sales broken down by Payment Method
category_payment = df.groupby(['Category', 'Payment_Method'])['Total_Sales'].sum().round(2)
category_payment_df = category_payment.reset_index().sort_values(
    by=['Category', 'Total_Sales'], ascending=[True, False])
category_payment_df

          Category    Payment_Method  Total_Sales
4            Books               UPI     13100.50
2            Books        Debit Card      9838.80
1            Books       Credit Card      6912.85
3            Books       Net Banking      5779.60
0            Books  Cash on Delivery      1160.65
8         Clothing       Net Banking     23812.75
6         Clothing       Credit Card     15072.60
9         Clothing               UPI     11292.25
7         Clothing        Debit Card     10795.00
5         Clothing  Cash on Delivery      8055.60
12     Electronics        Debit Card     31883.40
14     Electronics               UPI     26892.40
10     Electronics  Cash on Delivery     16519.00
11     Electronics       Credit Card     12294.20
13     Electronics       Net Banking      4497.00
18  Home & Kitchen       Net Banking     32180.25
19  Home & Kitchen               UPI     29687.10
17  Home & Kitchen        Debit Card     26209.85
16  Home & Kitchen       Credit Card     12919.30
15  Home & Kitchen  Cash on Delivery     12333.40
21          Sports       Credit Card     59341.30
23          Sports       Net Banking     30101.65
22          Sports        Debit Card     19337.85
24          Sports               UPI     15191.00
20          Sports  Cash on Delivery     12054.65

In [30]:
# City-wise sales broken down by Category (pivot table view)
city_category_pivot = pd.pivot_table(
    df, values='Total_Sales', index='City', columns='Category',
    aggfunc='sum', fill_value=0
).round(2)
city_category_pivot

Category       Books  Clothing  Electronics  Home & Kitchen    Sports
City
Ahmedabad    1998.00      0.00      6205.10         3822.45   2763.15
Bengaluru    3707.55      0.00      3820.75         5996.00      0.00
Bhubaneswar     0.00      0.00      6598.00            0.00      0.00
Chandigarh    449.10      0.00     19689.40         5698.10   8703.05
Chennai         0.00   9015.10      8034.30        14895.60  15548.20
Delhi        2644.70  21590.00         0.00         6648.10      0.00
Hyderabad       0.00      0.00     10193.20        19594.40  29288.85
Jaipur          0.00    799.00      5938.20         1398.00  17398.80
Jammu         999.00   6076.20      3134.05            0.00   5850.50
Kochi        5840.10  15453.00         0.00         6469.15   9495.25
Kolkata      6754.75      0.00      7043.50         6370.75      0.00
Lucknow      3085.70  10620.75      9496.20        10497.00  12495.00
Mumbai       2245.50   2278.15      9895.00        13044.15  13995.00
Pune         7269.80      0.00      2038.30        17707.90  14892.55
Srinagar     1798.20   3196.00         0.00         1188.30   5596.10

## 11. Identifying Specific Orders & Top Performers

In [31]:
# Specific order lookup - e.g., Order_ID = 1013
specific_order = df[df['Order_ID'] == 1013]
specific_order

,Order_ID,Order_Date,Customer,City,Region,Category,Product,Quantity,Unit_Price,Discount_Percent,Total_Sales,Rating,Payment_Method
12,1013,2026-03-09,Maryam Khan,Lucknow,North,Clothing,Jacket,5,2499,15,10620.75,4.8,Net Banking

In [32]:
# Top 3 products within EACH category (by total sales)
top3_per_category = (
    df.groupby(['Category', 'Product'])['Total_Sales']
    .sum()
    .reset_index()
    .sort_values(['Category', 'Total_Sales'], ascending=[True, False])
    .groupby('Category')
    .head(3)
)
top3_per_category

          Category              Product  Total_Sales
0            Books        Atomic Habits     11590.65
3            Books   Python Programming      7527.45
4            Books        The Alchemist      7485.00
6         Clothing               Jacket     47106.15
8         Clothing              T-Shirt      7790.25
5         Clothing               Hoodie      7675.20
12     Electronics  Wireless Headphones     33877.40
9      Electronics  Mechanical Keyboard     26489.40
11     Electronics          Smart Watch     15670.25
14  Home & Kitchen         Coffee Maker     51610.25
15  Home & Kitchen      Electric Kettle     26382.40
16  Home & Kitchen        Mixer Grinder     25341.55
18          Sports          Cricket Bat     41483.40
21          Sports        Running Shoes     41285.25
19          Sports         Dumbbell Set     30184.90

In [33]:
# Orders that are both high value (>7000) AND highly rated (>=4.5)
premium_orders = df[(df['Total_Sales'] > 7000) & (df['Rating'] >= 4.5)].sort_values(
    by='Total_Sales', ascending=False)
print(f"Premium orders found: {len(premium_orders)}")
premium_orders[['Order_ID', 'Product', 'City', 'Total_Sales', 'Rating']]

Premium orders found: 10

    Order_ID        Product       City  Total_Sales  Rating
12      1013         Jacket    Lucknow     10620.75     4.8
47      1048   Coffee Maker    Lucknow     10497.00     5.0
79      1080         Jacket      Delhi      9996.00     4.6
37      1038   Dumbbell Set       Pune      9495.25     5.0
9       1010         Jacket      Kochi      8996.40     4.7
56      1057   Coffee Maker    Chennai      8922.45     4.5
92      1093    Cricket Bat  Hyderabad      8496.60     4.5
13      1014  Running Shoes     Jaipur      8397.00     4.6
32      1033  Mixer Grinder       Pune      8097.30     4.7
18      1019         Jacket    Chennai      7497.00     4.7

## 12. Summary Table of Overall Key Metrics

In [34]:
summary = pd.DataFrame({
    'Metric': ['Total Sales', 'Average Sales per Order', 'Highest Sale', 'Lowest Sale',
               'Total Quantity Sold', 'Number of Orders', 'Top Category', 'Top City',
               'Top Product', 'Most Used Payment Method'],
    'Value': [
        f"₹{total_sales:,.2f}",
        f"₹{average_sales:,.2f}",
        f"₹{highest_sale:,.2f}",
        f"₹{lowest_sale:,.2f}",
        f"{total_quantity} units",
        f"{number_of_orders}",
        top_category,
        top5_cities.index[0],
        top5_products.index[0],
        most_popular_payment
    ]
})
summary

                     Metric         Value
0               Total Sales   ₹447,262.95
1   Average Sales per Order     ₹4,472.63
2              Highest Sale    ₹13,995.00
3               Lowest Sale       ₹449.10
4       Total Quantity Sold     294 units
5          Number of Orders           100
6              Top Category        Sports
7                  Top City     Hyderabad
8               Top Product  Coffee Maker
9  Most Used Payment Method           UPI

## 13. Observations

Based on the analysis above:

1. **Category performance:** One category clearly generates the highest total sales among all categories (see Section 6 output), indicating strong customer demand relative to other segments — though this should be weighed against the number of orders and average order value per category.
2. **Geographic concentration:** Sales are not evenly distributed across cities — a small number of cities account for a disproportionately large share of total revenue, suggesting these are priority markets for marketing and inventory focus.
3. **Product-level insight:** A handful of products dominate total sales, and the product with the highest total sales isn't always the one with the highest quantity sold — this points to differences in unit price and order size (a good pricing/bundling insight).
4. **Payment behavior:** One payment method is used considerably more than others, which could reflect customer trust/convenience and may guide which payment options to promote or optimize for a smoother checkout experience.
5. **Discount and satisfaction link:** Orders combining a discount with a high customer rating (≥4.5) suggest that reasonable discounting doesn't hurt satisfaction — and may even support it — useful for future promotional strategy.
6. **Order value spread:** There is a wide gap between the highest and lowest single-order sale values, showing the dataset contains both small individual purchases and large bulk/high-ticket orders, which is typical of a mixed-category e-commerce store.